#!/usr/bin/env python

import json
import db

configInfo = {"name": "",
              "height": 0,
              "weight": 0,
              "activity_level": "",
              "cals_a_day": 0
}

print("Welcome to the calorie tracker! \n Fetching information...")
try:
    with open("config.json") as f:
        print("hello world!")
except:
    print("No file found")
    
